apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yezgyulku-go 
  janus-idp.io/tekton: yezgyulku-go
  backstage.io/kubernetes-id: yezgyulku-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yezgyulku-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  